name: Build Qt C++ App (Cross-platform)

# Déclenche le workflow seulement si des fichiers sources ou CMake changent
on:
  push:
    branches: [ "master", "main" ]
    paths:
      - "src/**"
      - "include/**"
      - "CMakeLists.txt"
  pull_request:
    branches: [ "master", "main" ]
    paths:
      - "src/**"
      - "include/**"
      - "CMakeLists.txt"
  workflow_dispatch:  # permet de lancer manuellement

jobs:
  build-linux:
    name: Build on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '6.6.2'
          host: 'linux'

      - name: Configure CMake
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -G "Ninja"

      - name: Build
        run: cmake --build build

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: linux-build
          path: build/

  build-windows:
    name: Build on Windows
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '6.6.2'
          host: 'windows'

      - name: Configure CMake
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -G "Ninja"

      - name: Build
        run: cmake --build build

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows-build
          path: build/

  build-macos:
    name: Build on macOS
    runs-on: macos-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '6.6.2'
          host: 'mac'

      - name: Configure CMake
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -G "Ninja"

      - name: Build
        run: cmake --build build

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: macos-build
          path: build/
