name: Build Qt C++ App

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Installer Qt6 avec OpenGL
      - name: Setup Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '6.6.0'       # Choisir la version Qt
          host: 'linux'
          modules: 'qtbase,qtdeclarative,qtwidgets,qtgui,qtmultimedia,qtcharts,qttools'

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential cmake ninja-build libgl1-mesa-dev libglu1-mesa-dev

      - name: Configure CMake
        run: |
          mkdir -p build
          cd build
          cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=$HOME/Qt/6.6.0/gcc_64

      - name: Build
        run: |
          cd build
          ninja

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      # Installer Visual Studio Build Tools
      - name: Setup Visual Studio
        uses: microsoft/setup-msbuild@v1
        with:
          vs-version: '2022'

      # Installer Qt6
      - name: Setup Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '6.6.0'
          host: 'windows'
          arch: 'win64_msvc'
          modules: 'qtbase,qtdeclarative,qtwidgets,qtgui,qtmultimedia,qtcharts,qttools'

      # Installer Python + dépendances pip
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install py7zr==0.16.1

      # Build C++ avec CMake et Qt
      - name: Configure CMake
        run: |
          mkdir build
          cd build
          cmake .. -G "Visual Studio 17 2022" -A x64 -DCMAKE_PREFIX_PATH="C:/Qt/6.6.0/msvc_64"

      - name: Build
        run: |
          cmake --build build --config Release

  build-macos:
    name: Build macOS
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Qt
        run: |
          brew update
          brew install qt@6 cmake ninja

      - name: Configure CMake
        run: |
          mkdir build
          cd build
          cmake .. -G "Ninja" -DCMAKE_PREFIX_PATH="/usr/local/opt/qt@6" -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-build
          path: build/
